apiVersion: v1
kind: Secret
metadata:
  name: db-monitor-openstack
type: Opaque
stringData:
  OS_AUTH_TYPE: "v3applicationcredential"
  OS_AUTH_URL: "<replace me>"
  OS_IDENTITY_API_VERSION: "3"
  OS_REGION_NAME: "<replace me>"
  OS_INTERFACE: "public"
  OS_APPLICATION_CREDENTIAL_ID: "<replace me>"
  OS_APPLICATION_CREDENTIAL_SECRET: "<replace me>"